//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JacksMarvel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblUser
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public Nullable<System.DateTime> AccountCreationDate { get; set; }
        public string EmailAddress { get; set; }
        public Nullable<System.DateTime> LastLoginDateTime { get; set; }
        public Nullable<int> LoginCount { get; set; }
    }
}
